$URL = "http://*****:9801/MDTMonitorData/Computers"

function GetMDTData { 
  $Data = Invoke-RestMethod $URL

  $counter = 0
  foreach($property in ($Data.content.properties)) { 
    $counter++
    $StartTime = [datetime]$property.StartTime.'#text'
    $EndTime = [datetime]$property.EndTime.'#text'
    $TimeTaken = $EndTime - $StartTime
    $TimeTakenString = '{0:hh\:mm\:ss}' -f $TimeTaken
    New-Object PSObject -Property @{ 
      Name = $($property.Name); 
      PercentComplete = $($property.PercentComplete.'#text'); 
      Warnings = $($property.Warnings.'#text'); 
      Errors = $($property.Errors.'#text'); 
      DeploymentStatus = $( 
        Switch ($property.DeploymentStatus.'#text') { 
          1 { "Active/Running" } 
          2 { "Failed" } 
          3 { "Successfully completed" } 
          Default { "Unknown" } 
        } 
      ); 
      StartTime = $StartTime -replace "T"," "; 
      EndTime = $EndTime -replace "T"," "; 
      TimeTaken = $TimeTakenString
      CurrentStep = $($property.CurrentStep.'#text')
      TotalSteps = $($property.TotalSteps.'#text')
    } 
  } 
} 

$Head = @"
<style>
BODY{background-color: #f2f2f2; font-family: Arial, sans-serif;}
TABLE{border-collapse: collapse; width: 100%;}
TH{background-color: #4CAF50; color: white; text-align: left; padding: 8px;}
TD{border: 1px solid #dddddd; padding: 8px;}
TR:nth-child(even){background-color: #f2f2f2;}
TR:hover{background-color: #ddd;}
.successful {background-color: green;}
.failed {background-color: red;}
.successful-first {background-color: lightgreen;}
.failed-first {background-color: pink;}
</style>
"@

$Title = "Labor Deployment Status"

$FirstRecordProcessed = $false

GetMDTData | ForEach-Object {
    $row = $_
    if($row.DeploymentStatus -eq "Successfully completed" -and !$FirstRecordProcessed) {
        $row = $row.ToString().Replace("<tr>", "<tr class='successful-first'>")
        $FirstRecordProcessed = $true
    }
    elseif($row.DeploymentStatus -eq "Failed" -and !$FirstRecordProcessed) {
        $row = $row.ToString().Replace("<tr>", "<tr class='failed-first'>")
        $FirstRecordProcessed = $true
    }
    elseif($row.DeploymentStatus -eq "Successfully completed") {
        $row = $row.ToString().Replace("<tr>", "<tr class='successful'>")
    }
    elseif($row.DeploymentStatus -eq "Failed") {
        $row = $row.ToString().Replace("<tr>", "<tr class='failed'>")
    }
    $_
} | ConvertTo-Html  `
-Title $Title  `
-Head $Head  `
-Body (Get-Date -UFormat "%d.%m.%Y | %T ")  `
-PreContent "<H2>Labor Deployment Status für: $ENV:COMPUTERNAME </H2><P>Generated by Power of the Force!</P>"  `
-PostContent "<P></P>"  `
-Property Name,DeploymentStatus,PercentComplete,Warnings,Errors,StartTime,EndTime,TimeTaken,CurrentStep,TotalSteps |
Out-File -FilePath C:\inetpub\wwwroot\default.htm -Encoding utf8
